"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {ThemeProvider} from "../components/theameProvider"
import { ModeToggle } from "@/components/theameToggler";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {pathname !== "/" && (
            <div className="flex flex-row items-end">
              {
                pathname == "/meal"  && <h3 className="flex-1 pt-2 text-md md:text-3xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-green-600 via-green-500 to-emerald-600 text-center">MealMind</h3>
              }
              <div className="pt-2 pl-2">
                <ModeToggle />
              </div>
            </div>
          )}
          {children}

        </ThemeProvider>
      </body>
    </html>
  );
}
